##Install Files on Remote Nodes
- include: InstallGrafana.yml
  tags:
      - install

##Start Go Exporter on Remote Nodes
- include: start.yml
  tags:
      - start

##Remove Install Files on Remote Nodes
- include: clean.yml
  tags:
      - clean

- meta: flush_handlers

- name: Wait 5 seconds to come up
  pause: seconds=5

- name: Wait for Grafana to startup
  wait_for: host={{ansible_default_ipv4.address}} port=3000 delay=1 connect_timeout=1
